In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

In [ ]:
#Choosing dimensions, clusters and No.of training samples.
N = 1000
D = 2
K = 3
#Generating the dataset
X = np.random.ranf((N,D))

In [ ]:
#Initialising Theta parameters
mu = np.random.randint(10,size=(K,D))
sigma = np.random.randint(10,size=(K,D,D))
pi = np.random.dirichlet(np.ones(K),size=1)[0]

In [ ]:
#Function for calculating pdf of multivariate gaussian
def gaussian(x,u,s,D):
    x.reshape(2,1)
    u.reshape(2,1)
    det = abs(np.linalg.det(s))**0.5
    inv = np.linalg.pinv(s)
    const = (2*np.pi)**(D/2)
    temp1 = const*det
    temp2 = np.exp((-0.5)*np.matmul((x-u).reshape(1,2),np.matmul(inv,(x-u).reshape(2,1))))
    temp = temp2/temp1
    return temp

In [ ]:
#Expectation Maximization for estimating Gaussian Mixture Model parameters
def GMM(X,mu,sigma,pi):
    mu_new = np.zeros((K,D))
    sigma_new = np.zeros((K,D,D))
    pi_new = np.zeros(K)
    #Estimating gamma parameter from theta parameters
    gamma = np.zeros((N,K))
    for i in range(N):
        den1 = 0
        for k in range(K):
            den1 += gaussian(X[i][:],mu[k][:],sigma[k][:][:],D)*pi[k]
        for j in range(K):
            temp = gaussian(X[i][:],mu[j][:],sigma[j][:][:],D)*pi[j]
            temp = temp/den1
            gamma[i][j] = temp
    #Updating theta parameters from gamma
    for j in range(K):
        den2 = 0
        for i in range(N):
            den2 += gamma[i][j]
        num1 = 0
        num2 = np.zeros((D,D))
        for i in range(N):
            num1 +=  gamma[i][j]*X[i][:]
        mu_new[j][:] = num1/den2
        for i in range(N):
            num2 = np.add(num2,gamma[i][j]*np.matmul(np.subtract(X[i][:],mu_new[j][:]).reshape(2,1),np.subtract(X[i][:],mu_new[j][:]).reshape(1,2)))
        sigma_new[j][:][:] = num2/den2
        pi_new[j] = den2/N
    print('Updated Sigma',sigma_new)
    print('Updated Pi',pi_new)
    print('Updated Mean',mu_new)
    return mu_new,sigma_new,pi_new

In [ ]:
e = None
print(sigma)
like = 0
for i in range(N):
    for j in range(K):
        like += pi[j]*gaussian(X[i],mu[j],sigma[j][:][:],D)
print(like)
count = 0
while(e == None or e > 0.01):
    print('Iteration:',count)
    count += 1
    mu_new,sigma_new,pi_new = GMM(X,mu,sigma,pi)
    like_new = 0
    for i in range(N):
        for j in range(K):
            like_new += pi_new[j]*gaussian(X[i],mu_new[j],sigma_new[j][:][:],D)
    e = abs(like - like_new)
    like = like_new
    mu,sigma,pi = mu_new,sigma_new,pi_new

[[[2 8]
  [8 2]]

 [[0 2]
  [5 2]]

 [[0 5]
  [3 2]]]
[[22.35741632]]
Iteration: 0
Updated Sigma [[[0.08067713 0.00198115]
  [0.00198115 0.08335726]]

 [[0.06883349 0.00063421]
  [0.00063421 0.08149058]]

 [[0.08057635 0.00117456]
  [0.00117456 0.08262488]]]
Updated Pi [0.64279096 0.27817038 0.07903866]
Updated Mean [[0.4720784  0.50602426]
 [0.64704326 0.47413569]
 [0.46198437 0.46882272]]
Iteration: 1
Updated Sigma [[[0.0817704  0.00201142]
  [0.00201142 0.08346022]]

 [[0.06401625 0.00070322]
  [0.00070322 0.08127185]]

 [[0.08134301 0.00126852]
  [0.00126852 0.08256507]]]
Updated Pi [0.64223464 0.2787741  0.07899126]
Updated Mean [[0.46976026 0.50605264]
 [0.65270276 0.47415705]
 [0.45951527 0.46873796]]
Iteration: 2
Updated Sigma [[[0.08190246 0.00206374]
  [0.00206374 0.08348387]]

 [[0.06028136 0.00078886]
  [0.00078886 0.081231  ]]

 [[0.0812897  0.00138478]
  [0.00138478 0.08253594]]]
Updated Pi [0.64184366 0.27917963 0.07897671]
Updated Mean [[0.46619184 0.50604508]
 [0.66168